### ISSUE TITLE
TODO (replace mongo 2.4 with mongo-cxx-driver)

### ISSUE THREAD

**Issue by alexbevi** [alexbevi/robomongo#4]
### TODO
- [ ] ensure build works for 32-bit systems
- [ ] ensure build works on Windows
- [ ] ensure build works on OSX
### FIXME (cmake)
- [ ] use non-system libboost
- [ ] fix `${CMAKE_COMMAND} -E copy_if_different` (can't get it to work without putting an absolute path in)
- [ ] generate the `mongo/config.h` and `mongo/version.h` files automatically
- [ ] generate the `mongo/base/error_codes.cpp|h` files automatically
